import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { IsaGeneratedModule, IsaGeneratedSharedModule } from './generated/module.js';
import { IsaValidator, registerValidationChecks } from './isa-validator.js';
import { IsaCompletionProvider } from './isa-completion-provider.js';
import { IsaScopeProvider } from './isa-scope-provider.js';
import { IsaDocumentProcessor } from './isa-document-processor.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type IsaAddedServices = {
    validation: {
        IsaValidator: IsaValidator
    },
    completion: {
        CompletionProvider: IsaCompletionProvider
    },
    references: {
        ScopeProvider: IsaScopeProvider
    },
    workspace: {
        DocumentProcessor: IsaDocumentProcessor
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type IsaServices = LangiumServices & IsaAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const IsaModule: Module<IsaServices, PartialLangiumServices & IsaAddedServices> = {
    validation: {
        IsaValidator: () => new IsaValidator()
    },
    completion: {
        CompletionProvider: (services) => new IsaCompletionProvider(services)
    },
    references: {
        ScopeProvider: (services) => new IsaScopeProvider(services)
    },
    workspace: {
        DocumentProcessor: (services) => new IsaDocumentProcessor(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createIsaServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Isa: IsaServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        IsaGeneratedSharedModule
    );
    const Isa = inject(
        createDefaultModule({ shared }),
        IsaGeneratedModule,
        IsaModule
    );
    shared.ServiceRegistry.register(Isa);
    registerValidationChecks(Isa);
    
    // Hook into document builder to process includes BEFORE documents are fully built
    // This ensures included files are available when resolving cross-references during linking
    const documentProcessor = Isa.workspace.DocumentProcessor;
    let isProcessingIncludes = false; // Flag to prevent recursive calls
    const originalBuild = shared.workspace.DocumentBuilder.build.bind(shared.workspace.DocumentBuilder);
    shared.workspace.DocumentBuilder.build = async (documents, options, cancelToken) => {
        // If we're already processing includes (called from document processor), just build normally
        if (isProcessingIncludes) {
            return await originalBuild(documents, options, cancelToken);
        }
        
        // Step 1: Build documents with parsing only (no linking/validation) to extract includes
        // We need to parse first to get the AST and extract include directives
        // Note: We can't skip linking completely, but we'll rebuild after processing includes
        await originalBuild(documents, { ...options, validation: false }, cancelToken);
        
        // Step 2: Process includes for all documents (this loads included files)
        // We need to do this AFTER parsing but BEFORE full linking
        isProcessingIncludes = true;
        try {
            for (const doc of documents) {
                try {
                    await documentProcessor.processDocument(doc);
                } catch (error) {
                    // Let validation handle errors
                }
            }
        } finally {
            isProcessingIncludes = false;
        }
        
        // Step 3: Now rebuild all documents (original + included) with full linking
        // At this point, included files are loaded, so cross-references can be resolved
        // First, invalidate all documents to force re-linking
        const allDocuments = Array.from(shared.workspace.LangiumDocuments.all);
        
        // Invalidate all documents to force re-linking with the new included files
        for (const doc of allDocuments) {
            shared.workspace.LangiumDocuments.invalidateDocument(doc.uri);
        }
        
        // Now rebuild all documents with full linking and validation
        const result = await originalBuild(allDocuments, options, cancelToken);
        
        return result;
    };
    
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Isa };
}
